// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {problems} from '../models';
import {types} from '../models';

export function CreateProblem(arg1:problems.CreateProblemRequest):Promise<types.APIResponse_Myapp_api_problems_ProblemResponse_>;

export function Greet(arg1:string):Promise<string>;
